# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nathan Lawrence
email: nathan@nathanlawrence.org
description: > # this means to ignore newlines until "baseurl:"
  Web developer, photographer and documentary filmmaker.
  Writing code to make public media more awesome.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.nathanlawrence.org" # the base hostname & protocol for your site
twitter_username: nathanblawrence
github_username:  nathanlawrence

# Build settings
markdown: kramdown
